name: Cache, Build & Test
on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: Cache, Build & Test
    env:
      SCHEME: "POC-SPM-Actions"
      DEVICE: "iPhone 12"
      DERIVED_DATA_PATH: "DerivedData"

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cache
        uses: actions/cache@v2
        with:
          id: spm-cache
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
          
      - name: Build
        run: xcodebuild clean test -project POC-SPM-Actions.xcodeproj -scheme POC-SPM-Actions -destination "platform=iOS Simulator,name=iPhone 11 Pro"
